# 1.张量

In [1]:
import torch as t
import numpy as np

In [2]:
?t.tensor

In [3]:
a = t.tensor(1.0, dtype=t.float)
b = t.tensor(1, dtype=t.long)
c = t.tensor(1.0, dtype=t.int8)
print(a, b, c)

tensor(1.) tensor(1) tensor(1, dtype=torch.int8)


In [4]:
d = t.FloatTensor(2, 3)
e = t.IntTensor(2)
f = t.IntTensor([1, 2, 3, 4])
print(d, '\n', e, '\n', f)

tensor([[9.2755e-39, 1.0561e-38, 1.1020e-38],
        [8.4490e-39, 1.0286e-38, 6.2450e-39]]) 
 tensor([         0, 1072693248], dtype=torch.int32) 
 tensor([1, 2, 3, 4], dtype=torch.int32)


In [3]:
g = np.array([[1, 2, 3], [4, 5, 6]])
h = t.tensor(g)
print(h)
i = t.from_numpy(g)
print(i)
j = h.numpy()
print(j)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
[[1 2 3]
 [4 5 6]]


In [4]:
k = t.rand(2, 3)
l = t.ones(2, 3)
m = t.zeros(2, 3)
n = t.arange(0, 10, 2)
print(k, '\n', l, '\n', m, '\n', n)

tensor([[0.2231, 0.4210, 0.4414],
        [0.5629, 0.9018, 0.1703]]) 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 
 tensor([0, 2, 4, 6, 8])


In [7]:
print(k.shape)
print(k.size())

torch.Size([2, 3])
torch.Size([2, 3])


In [8]:
o = t.add(k, l)
print(o)

tensor([[1.2231, 1.4210, 1.4414],
        [1.5629, 1.9018, 1.1703]])


In [9]:
print(o[:, 1])
print(o[0, :])

tensor([1.4210, 1.9018])
tensor([1.2231, 1.4210, 1.4414])


In [10]:
print(o.view(3, 2))
print(o.view(-1, 2))

tensor([[1.2231, 1.4210],
        [1.4414, 1.5629],
        [1.9018, 1.1703]])
tensor([[1.2231, 1.4210],
        [1.4414, 1.5629],
        [1.9018, 1.1703]])


In [13]:
p = t.arange(1, 3).view(1, 2)
print(p)
q = t.arange(1, 4).view(3, 1)
print(q)
# [1, 2]会被复制成3份，变成[3， 2]
print(p + q)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [14]:
print(o)
r = o.unsqueeze(1)
print(r)
print(r.shape)

tensor([[1.2231, 1.4210, 1.4414],
        [1.5629, 1.9018, 1.1703]])
tensor([[[1.2231, 1.4210, 1.4414]],

        [[1.5629, 1.9018, 1.1703]]])
torch.Size([2, 1, 3])


In [15]:
s = r.squeeze(0)
print(s)
print(s.shape)

tensor([[[1.2231, 1.4210, 1.4414]],

        [[1.5629, 1.9018, 1.1703]]])
torch.Size([2, 1, 3])


In [17]:
t = r.squeeze(1)
print(t)
print(t.shape)

tensor([[1.2231, 1.4210, 1.4414],
        [1.5629, 1.9018, 1.1703]])
torch.Size([2, 3])


# 2.自动求导

In [1]:
#import torch
x1 = t.tensor(1.0, requires_grad=True)
x2 = t.tensor(2.0, requires_grad=True)
y = x1 + 2*x2
print(y)

tensor(5., grad_fn=<AddBackward0>)


In [2]:
print(x1.requires_grad)
print(x2.requires_grad)
print(y.requires_grad)

True
True
True


In [3]:
print(x1.grad.data)
print(x2.grad.data)
print(y.grad.data)

AttributeError: 'NoneType' object has no attribute 'data'

In [4]:
x1

tensor(1., requires_grad=True)

In [5]:
y = x1 + 2*x2
y.backward()
print(x1.grad.data)
print(x2.grad.data)

tensor(1.)
tensor(2.)


In [7]:
y = x1 + 2*x2
y.backward()
print(x1.grad.data)
print(x2.grad.data)

tensor(2.)
tensor(4.)


In [8]:
y = x1 + 2*x2
y.backward()
print(x1.grad.data)
print(x2.grad.data)

tensor(3.)
tensor(6.)


In [9]:
y = x1 + 2*x2
y.backward()
print(x1.grad.data)
print(x2.grad.data)

tensor(4.)
tensor(8.)


In [10]:
x1 = torch.tensor(1.0, requires_grad=False)
x2 = torch.tensor(2.0, requires_grad=False)
y = x1 + 2*x2
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn